In [3]:
from scipy.sparse import csr_matrix
import numpy as np

In [4]:
indptr  = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data    = np.array([1, 2, 3, 4, 5, 6])
csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()
# array([[1, 0, 2],
#        [0, 0, 3],
#        [4, 5, 6]])

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [5]:
csr_matrix((data, indices, indptr)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [11]:
indptr  = np.array([0, 2, 1, 2, 2, 1, 1, 0])
indices = np.array([0, 2, 1, 0, 1, 2, 1, 0])
data    = np.array([1, 2, 3, 4, 5, 6, 7, -1])
csr_matrix((data, (indices, indptr))).toarray()

array([[ 0,  0,  4],
       [ 0, 10,  5],
       [ 0,  6,  2]], dtype=int64)

____

In [11]:
import pandas as pd
import numpy as np
import os

In [1]:
import tensorflow as tf

In [10]:
a = pd.Series([1, 2, 3, 4, 5, 6]).astype(np.int32)
a = tf.constant(a, shape=[2, 3])
a  # 2-D tensor

b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
b  # 2-D tensor

c = tf.matmul(a, b)
c  # `a` * `b`




<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [7]:
a

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [8]:
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [13]:
processed_data_dir = '/Users/hitoshinagano/Documents/MercadoLibre_competicao/notebooks/../data/processed'
lang = 'pt'

item_data_embs_only_fn = 'item_data_embs_only.pkl'
item_data_embs_only_fp = os.path.join(processed_data_dir, item_data_embs_only_fn)
item_data = pd.read_pickle(item_data_embs_only_fp)

item_data = item_data[item_data.lang_domain == lang].copy()
item_data.drop('lang_domain', axis = 1, inplace = True)
item_data.set_index('item_id', inplace = True)

In [17]:
item_data = item_data.title_embs.apply(pd.Series)

In [15]:
interim_data_dir = '/Users/hitoshinagano/Documents/MercadoLibre_competicao/notebooks/../data/interim'
query_embs = pd.read_pickle(os.path.join(interim_data_dir, 'query_embs_sample.pkl'))

In [19]:
item_data.head()

0         1         2         3         4         5         6   \
item_id                                                                         
2076351  0.151978  0.024384  0.274902 -0.141113 -0.124207  0.159912 -0.022247   
234839  -0.234741  0.019241 -0.047821 -0.027756 -0.223022  0.024460 -0.028580   
442139  -0.043030 -0.099792  0.124451 -0.077209 -0.120361 -0.082825  0.150024   
1893085  0.124695 -0.003956  0.297852 -0.111145 -0.058411 -0.222778 -0.119568   
1185052  0.041840  0.106140  0.176147 -0.014366 -0.251221 -0.148193 -0.057434   

               7         8         9   ...        40        41        42  \
item_id                                ...                                 
2076351 -0.064392 -0.322998 -0.088074  ...  0.005753 -0.058167 -0.194092   
234839  -0.046173 -0.321045 -0.050385  ...  0.116821  0.006920 -0.174072   
442139   0.071167 -0.265137 -0.066895  ... -0.051392 -0.035034 -0.057800   
1893085  0.048157 -0.188599 -0.020920  ... -0.049377 -0.147827 -0.079407   
1185052 -0.183594  0.000953 -0.081726  ... -0.071228 -0.295898 -0.244995   

               43        44        45        46        47        48        49  
item_id                                                                        
2076351  0.141113  0.088257  0.032349  0.175903  0.032593  0.251709  0.155396  
234839  -0.058899  0.009262 -0.132202  0.222046  0.145752  0.274658  0.058929  
442139   0.120972 -0.079041  0.104614  0.221191  0.120483  0.366699  0.197510  
1893085  0.013885 -0.031052  0.055267  0.139404  0.111572  0.167480  0.155518  
1185052 -0.043579  0.016953 -0.073730  0.138550  0.167236  0.054718  0.106506  

[5 rows x 50 columns]

In [20]:
query_embs.head()

0         1         2         3         4         5         6   \
seq                                                                            
400021  0.167969 -0.047180  0.126099 -0.160156 -0.184204 -0.115662  0.000008   
400065  0.008041 -0.061127  0.070190 -0.056152 -0.066772 -0.007740  0.016327   
400140 -0.073792 -0.143311 -0.050049 -0.053619 -0.077881 -0.102356  0.103271   
400564  0.004425  0.146118 -0.077820 -0.035278 -0.046143  0.051239  0.066345   
400627 -0.009529  0.055389  0.032013 -0.100159 -0.124451  0.046967 -0.065491   

              7         8         9   ...        40        41        42  \
seq                                   ...                                 
400021 -0.063538 -0.273438  0.063416  ...  0.085083  0.053192 -0.084961   
400065 -0.040863 -0.113281  0.008583  ... -0.021561  0.039185 -0.058411   
400140 -0.244141  0.164062  0.094482  ...  0.210327  0.109131 -0.276611   
400564 -0.070496 -0.142212 -0.051361  ... -0.013802  0.023407 -0.094238   
400627  0.071838  0.000756  0.006168  ...  0.217773  0.246826  0.023453   

              43        44        45        46        47        48        49  
seq                                                                           
400021  0.058624 -0.086304  0.188354  0.142090  0.312256  0.074890  0.164917  
400065  0.102722 -0.039368  0.024734 -0.018234  0.083679  0.100586  0.081909  
400140  0.170654 -0.333252  0.033356  0.089294  0.275146 -0.098206  0.047455  
400564 -0.043976 -0.126099 -0.103821  0.301758  0.066711  0.147949 -0.052063  
400627  0.054047  0.114685  0.098022  0.331055 -0.048096  0.211914  0.128418  

[5 rows x 50 columns]

In [ ]:
# scores = item_data @ query_embs.T

In [22]:
a = item_data
b = query_embs.T

In [23]:
a.shape, b.shape

((1723216, 50), (50, 101))

In [28]:
scores = tf.matmul(a, b)

In [30]:
scores = scores.numpy()

In [31]:
scores

array([[ 0.588  ,  0.2537 ,  0.0934 , ..., -0.05182,  0.2856 ,  0.2769 ],
       [ 0.3704 ,  0.1748 ,  0.1931 , ...,  0.2164 ,  0.2979 ,  0.273  ],
       [ 0.559  ,  0.268  ,  0.0882 , ...,  0.1307 ,  0.2266 ,  0.2905 ],
       ...,
       [ 0.2052 ,  0.03555,  0.3528 , ...,  0.2605 ,  0.2998 ,  0.1455 ],
       [ 0.5034 ,  0.1764 ,  0.4688 , ...,  0.2678 ,  0.723  ,  0.616  ],
       [ 0.8403 ,  0.3066 ,  0.3965 , ...,  0.2229 ,  0.398  ,  0.436  ]],
      dtype=float16)

In [32]:
scores = pd.DataFrame(scores, index = item_data.index, columns = query_embs.index)

In [33]:
scores

seq        400021    400065    400140    400564    400627    400748    400815  \
item_id                                                                         
2076351  0.587891  0.253662  0.093384  0.326416  0.359863  0.142456  0.466309   
234839   0.370361  0.174805  0.193115  0.489014  0.372803  0.165527  0.472412   
442139   0.559082  0.268066  0.088196  0.376221  0.402344  0.151367  0.605469   
1893085  0.741211  0.280273  0.128296  0.276611  0.276855  0.249268  0.465332   
1185052  0.385742  0.130737  0.262207  0.252930  0.091919  0.259033  0.202026   
...           ...       ...       ...       ...       ...       ...       ...   
1099649  0.459717  0.111511  0.562988  0.301025  0.229492  0.268066  0.114624   
1482187  0.526855  0.203735  0.314453  0.296631  0.149780  0.339600  0.359131   
1118904  0.205200  0.035553  0.352783  0.194946  0.209229  0.331299  0.052673   
237229   0.503418  0.176392  0.468750  0.312988  0.448975  0.429932  0.321289   
2010306  0.840332  0.306641  0.396484  0.365967  0.308350  0.210815  0.485107   

seq        400850    400974    401519  ...    412218    412328    412383  \
item_id                                ...                                 
2076351  0.308350  0.192383  0.651367  ...  0.274902  0.255615  0.377930   
234839   0.401611  0.290283  0.346436  ...  0.446777  0.154907  0.366943   
442139   0.233032  0.307861  0.617676  ...  0.281738  0.198853  0.356689   
1893085  0.349365  0.323730  0.650879  ...  0.227783  0.344971  0.523926   
1185052  0.311035  0.288330  0.431885  ...  0.287354  0.297852  0.357178   
...           ...       ...       ...  ...       ...       ...       ...   
1099649  0.358887  0.374756  0.134521  ...  0.200073  0.112183  0.318359   
1482187  0.492676  0.480713  0.368896  ...  0.386475  0.245728  0.452637   
1118904  0.108459  0.190430  0.090149  ...  0.232544  0.101501  0.268311   
237229   0.651855  0.436768  0.252197  ...  0.438477  0.297363  0.456543   
2010306  0.434570  0.325439  0.623047  ...  0.209473  0.237549  0.571777   

seq        412567    412660    412688    412869    412943    412983    412998  
item_id                                                                        
2076351  0.685059  0.344482  0.583008  0.189697 -0.051819  0.285645  0.276855  
234839   0.442627  0.447998  0.267822  0.126099  0.216431  0.297852  0.272949  
442139   0.718750  0.426025  0.437256  0.200928  0.130737  0.226562  0.290527  
1893085  0.797852  0.391846  0.646973  0.368164 -0.025024  0.539062  0.513184  
1185052  0.499756  0.222168  0.564941  0.213135 -0.049988  0.491211  0.366699  
...           ...       ...       ...       ...       ...       ...       ...  
1099649  0.252930  0.243164  0.339111  0.176758  0.305420  0.234985  0.316650  
1482187  0.485107  0.408447  0.415527  0.440430  0.097534  0.614258  0.582031  
1118904  0.174316  0.196289  0.171875  0.114929  0.260498  0.299805  0.145508  
237229   0.366699  0.431152  0.473389  0.420166  0.267822  0.723145  0.616211  
2010306  0.804688  0.404053  0.531738  0.395996  0.222900  0.397949  0.436035  

[1723216 rows x 101 columns]

----

### unused

In [14]:
# nlp = spacy.load('en_core_web_sm')

# from spacy_langdetect import LanguageDetector
# nlp.add_pipe(LanguageDetector(), name='language_detector', last=True)

# from langdetect import detect

In [15]:
# nlp = spacy.load('en_core_web_sm')

# from spacy_langdetect import LanguageDetector
# nlp.add_pipe(LanguageDetector(), name='language_detector', last=True)

# Evaluate using spacy_langdetect for QUERIES. 
# For titles it is much easier to get from MLB (Brasil) & MLM (Mexico) in the domain_id

# USING Spacy

# item_data_unique['lang'] = item_data_unique.title_lower.progress_apply(lambda x: nlp(' '.join(x.split()[:3]))._.language)
# item_data_unique['lang'] = item_data_unique.title_lower.progress_apply(lambda x: nlp(x)._.language)

# USING langdetect

# from langdetect import detect

# import dask.dataframe as dd
# from dask.distributed import Client
# client = Client()
# client

# def safe_detect(txt):
#     try:
#         return detect(txt)
#     except:
#         return 'detect error'

# item_data_unique_dd = dd.from_pandas(item_data_unique[['title_lower']], npartitions = 8)
# item_data_unique_dd['lang'] = item_data_unique_dd.title_lower.apply(safe_detect, meta=('title_lower', 'object'))

# %%time
# item_data_unique_lang = item_data_unique_dd.compute()
# # CPU times: user 11min 50s, sys: 1min, total: 12min 51s
# # Wall time: 2h 46min 56s

# saving interim item_data_unique_lang

# item_data_unique_lang_fn = 'item_data_unique_lang.pkl'
# item_data_unique_lang_fp = os.path.join(interim_data_dir, item_data_unique_lang_fn)
# item_data_unique_lang.to_pickle(item_data_unique_lang_fp)

# item_data_unique['lang'] = item_data_unique_lang['lang']
