In [3]:
from scipy.sparse import csr_matrix
import numpy as np

In [4]:
indptr  = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data    = np.array([1, 2, 3, 4, 5, 6])
csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()
# array([[1, 0, 2],
#        [0, 0, 3],
#        [4, 5, 6]])

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [5]:
csr_matrix((data, indices, indptr)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [11]:
indptr  = np.array([0, 2, 1, 2, 2, 1, 1, 0])
indices = np.array([0, 2, 1, 0, 1, 2, 1, 0])
data    = np.array([1, 2, 3, 4, 5, 6, 7, -1])
csr_matrix((data, (indices, indptr))).toarray()

array([[ 0,  0,  4],
       [ 0, 10,  5],
       [ 0,  6,  2]], dtype=int64)

----

In [1]:
import pandas as pd

In [17]:
df = pd.read_clipboard(encoding = 'utf-8', header = None, error_bad_lines = False, sep = ';')

In [19]:
df.columns = ['nome']

In [30]:
df[df.nome.str.contains('USP')].values

array([['Alves, M. Universidade de Sao Paulo - USP'],
       ['Andricopulo, Adriano Defini Universidade de Sao Paulo - USP'],
       ['Arêas, José Alfredo Gomes Universidade de Sao Paulo - USP'],
       ['Artaxo, Paulo Universidade de Sao Paulo - USP'],
       ['Augusto, Ohara Universidade de Sao Paulo - USP'],
       ['Azevedo, C. R.F. Universidade de Sao Paulo - USP'],
       ['Azevedo, Ricardo A. Universidade de Sao Paulo - USP'],
       ['Bagnato, V. S. Universidade de Sao Paulo - USP'],
       ['Barbosa, Fernando Universidade de Sao Paulo - USP'],
       ['Barbuy, B. Universidade de Sao Paulo - USP'],
       ['Benseñor, Isabela M. Universidade de Sao Paulo - USP'],
       ['Berlinck, Roberto G.S. Universidade de Sao Paulo - USP'],
       ['Blanchard, D. Caroline Universidade de Sao Paulo - USP'],
       ['Bonato, Pierina Sueli Universidade de Sao Paulo - USP'],
       ['Braga, Roberto R. Universidade de Sao Paulo - USP'],
       ['Bretas, Newton G. Universidade de Sao Paulo - USP'