In [3]:
from scipy.sparse import csr_matrix
import numpy as np

In [4]:
indptr  = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data    = np.array([1, 2, 3, 4, 5, 6])
csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()
# array([[1, 0, 2],
#        [0, 0, 3],
#        [4, 5, 6]])

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [5]:
csr_matrix((data, indices, indptr)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [11]:
indptr  = np.array([0, 2, 1, 2, 2, 1, 1, 0])
indices = np.array([0, 2, 1, 0, 1, 2, 1, 0])
data    = np.array([1, 2, 3, 4, 5, 6, 7, -1])
csr_matrix((data, (indices, indptr))).toarray()

array([[ 0,  0,  4],
       [ 0, 10,  5],
       [ 0,  6,  2]], dtype=int64)